### ISSUE TITLE
Install new packages with this version of lammps

### ISSUE THREAD

**Issue by fireballpoint1** [plumed/conda#1]
I wan to run a simulation on :
-  lammps with 
-  CVs defined in plumed 
-  using a custom **pair style** [nnp](https://github.com/CompPhysVienna/n2p2)

Installing nnp can only be done by copying the `.so` files for the pair style in the `lib` directory of lammps and then doing a:
```
make yes-user-nnp
make mpi
``` 
in `src` folder. ( *INFO* for some reason nnp install doesn't work with cmake )

**MY ISSUE**
I couldn't install `user-plumed` package on my lammps installation due to some reasons ( can give details if anyone is ready to help with this). Hence, I am using this pre-patched version.\
However, how do I install `user-nnp` package on this version when I don't have a structure like I would for doing a LAMMPS installation using `make`

**Comment by GiovanniBussi** [comment]
I am not sure I understand the question... Are you familiar with conda build? All the infos related to the lammps build are in [this directory](https://github.com/plumed/conda/tree/master/lammps). I think you could try to use conda build on your machine.

**Comment by fireballpoint1** [comment]
@GiovanniBussi I have updated my query. See if it makes sense now.

**Comment by GiovanniBussi** [comment]
I think you cannot do this using the precompiled plumed that you find here. You should find out how to compile the USER-PLUMED package.
